---
- name: Restart Nginx
  service: name=nginx state=restarted
  sudo: yes

- name: Restart Postfix
  service: name=postfix state=restarted
  sudo: yes

- name: Restart Fail2ban
  service: name=fail2ban state=restarted
  sudo: yes

- name: Restart SSH
  service: name=ssh state=restarted
  sudo: yes

- name: Restart UFW
  service: name=ufw state=restarted
  sudo: yes

- name: Restart MySQL
  service: name=mysql state=restarted
  sudo: yes

- name: Restart Warpspeed PHP-FPM
  command: service php5-fpm-{{ domain }} restart
  when: warpspeed_root is defined and warpspeed_root != "" and domain is defined
  sudo: yes

- name: Restart PHP-FPM
  command: service php5-fpm restart
  when: warpspeed_root is not defined or warpspeed_root == ""
  sudo: yes

- name: Reload Init Config
  command: initctl reload-configuration
  sudo: yes
  notify: Restart Warpspeed PHP-FPM

- name: Update Timezone
  command: dpkg-reconfigure -f noninteractive tzdata
  sudo: yes

- name: Turn on Swap
  command: swapon -ae
  sudo: yes
